project:
  type: website

website:
  site-url: https://ajay8005.github.io/personal-website/
  # google-analytics: G-B8G2041HSB
  sidebar:
    style: docked
    title: "AS Tutoring"
    logo: assets/AS-Tutoring.png
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/asharma2718
    contents:
      - href: index.qmd
        text: About Us
      - href: contact.qmd
        text: "Contact & Tutoring Services"
      - href: license.qmd
        text: License

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    include-in-header:
      - file: siteimprove.html
      - text: |
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
          />
